services:
  bot:
    build: .
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_URL=postgres://feurcoubeh:${POSTGRES_PASSWORD}@db:5432/feurcoubehdb
    restart: unless-stopped
